### ISSUE TITLE
Policy for coloring and defaults

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikely#30]
If no 'value' key and no 'default' key --> color red (lighter red than before)
Delete 'value' key when a field with no 'default'  key is deleted

**Comment by colehurwitz** [comment]
Don't let user run pipeline if any red fields exist

**Comment by colehurwitz** [comment]
Optional -> Provide number of red parameters for user to fill as a visual countdown

**Comment by rogerhurwitz** [comment]
Have not implemented run blocking if red fields exist, but did implement value/default policy as well as string to type conversions.

**Comment by rogerhurwitz** [comment]
Run blocking implemented if required parameters are missing.  Count of missing parameters is included as part of error message to user.
