### ISSUE TITLE
Reorganize for packaging.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikely#34]
Dear Roger and Cole,
I think you should reorganise the folder like a standard python  module into a subfolder.
So you could add a setup.py to make a package.

Python setup.py have a system to offer command command line interface 
see how I did it in this project:
https://github.com/samuelgarcia/ephyviewer

so you can after do
```
spikely
```

I can help.

best

Samuel

**Comment by colehurwitz** [comment]
This seems like a good idea. I can attempt something like this in a new branch and see how it looks

**Comment by rogerhurwitz** [comment]
Thanks for the pointers. Samuel.  I restructured the repository along the lines of ephyviewer.  Still needs more work, but it seems to be moving int he right direction.

**Comment by rogerhurwitz** [comment]
Should be up and running as of version 0.3.7

**Comment by samuelgarcia** [comment]
:)
