### ISSUE TITLE
Add a save button

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikely#37]
- for sorted data (in some format, maybe Phy as well)
- for config files (json)

**Comment by colehurwitz** [comment]
We can add an option to save to phy at the end. Currently, it saves the result to the sorted result to the given output folder and the curated result to the Phy format (but did not export to phy yet).

**Comment by rogerhurwitz** [comment]
With the addition of JSON pipeline file loading/saving and Exporter elements in v0.4.6+ have these issues been addressed?
