### ISSUE TITLE
Compatibility check before running a loaded pipeline.

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [SpikeInterface/spikely#55]
Under the current implementation, loading out-of-date pipline configuration files would be accepted by our app. However, it would raise error if the SpikeInterface packages are updated.

Meanwhile, the sorting algorithm in the configuration file maybe unavailable on the running app.

Thus, it's better to check the compatibility of the loaded pipeline model on the running app before running it.

**Comment by colehurwitz** [comment]
So two things are mentioned in this issue:

1. Check that versions of the spikeinterface packages are supported
2. Check to see if the SpikeElements (the Sorter, Extractor, etc.) are available in the current python distribution. So loading a pipeline that contains the Klusta sorter should not work if Klusta isn't installed on the system.

I agree with both checks.

**Comment by rogerhurwitz** [comment]
Something to consider, along with the actual parameters, spikely saves only the **class name** of the element and the **class name** of the underlying spike interface class.  Spikely does not save the instantiated objects associated with those classes.  That means when spikely loads the saved JSON file it attempts to instantiate the current version of those classes, not the version that was present when the file was saved.

**Comment by colehurwitz** [comment]
I see. Before instantiating, it can check to see if the class is installed.

class = get_class_from_name(name)
installed = class.installed

Or something like this.

**Comment by rogerhurwitz** [comment]
Added installation check and merged it into master.  Still need to do parameter_list comparison as a proxy for version matching at the spikeinterface class level.

**Comment by rogerhurwitz** [comment]
Now checks to make sure the element is installed and that the saved parameter list is the same as or a subset of the current element parameter list.  Added fix to master.  @Shawn-Guo-CN please test it, and close this issue if you are satisfied with the result.

**Comment by Shawn-Guo-CN** [comment]
I've tested the compatibility of latest master branch. It's cool, now. Thanks very much, @rogerhurwitz .
