### ISSUE TITLE
Unclear running status.

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [SpikeInterface/spikely#56]
Currently (version 0.5.2), it's hard to track the running status of pipeline models, as all the related information won't appear in the GUI. The inconvenience found yet:

1. Hard to tell whether a pipeline is done, even with the output from background console.

2. When a loaded pipeline is incompatible with the running Spikely, users have to refer to the background console to find out what is missing.

My suggestion for updating would be, use QTextEdit to display text from stdout as well as stderr.

**Comment by rogerhurwitz** [comment]
I added a messaging queue shared by parent and child processes to allow the process running the pipeline (child) to signal the app (parent) upon completion of run.  I hooked that queue up to a message box that serves as an indicator.  I have no idea of whether it will work on Windows. :)

**Comment by Shawn-Guo-CN** [comment]
> I added a messaging queue shared by parent and child processes to allow the process running the pipeline (child) to signal the app (parent) upon completion of run. I hooked that queue up to a message box that serves as an indicator. I have no idea of whether it will work on Windows. :)

The message box could work on Windows: it pops out after "run" button is clicked, and it could be closed manutally or automatically. This is very helpful. But, based on the current tests, I realised another issue #61 .

So, I close this issue but open a new one.

**Comment by Shawn-Guo-CN** [comment]
Just found a new problem. If the pipeline crashes in background, there won't be any signal from the child processes to the parent process. Thus: i) users may manually close the message box window; ii) the message box will be there forever. In neither case, the users could know that the pipeline crashes in background.

This could be solved if we just print the stdout from that pipeline, as mentioned in #61 .

**Comment by colehurwitz** [comment]
Moving to new issue #67
