### ISSUE TITLE
Specify versions of dependencies in setup.py

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [SpikeInterface/spikely#62]
Currently (v0.5.2), *setup.py* only specifies the dependency packages of Spikely, but **no specific versions**. So, the pip may automatically install the latest version of these depedency packages, which may be incompatible.

**Comment by rogerhurwitz** [comment]
Added specific versions in tip of master.

```
   install_requires=[
        'PyQt5>=5.12.3',
        'spikeextractors>=0.7.0',
        'spiketoolkit>=0.5.0',
        'spikesorters>=0.2.0'
    ],
```
