### ISSUE TITLE
Change the names ("Extractor" and "Exporter") in the far left pull-down menu.

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [SpikeInterface/spikely#63]
Currently (v0.5.2), names of modules in the far left pull-down menu (in main window) are "Extractors", "Preprocessors", "Sorters", "Postprocessors" and "Exporters". But, as our only support standard policy reightnow, and only RordingExtractors/SortingExporters are contained in it, it's better to change the names, "Extractors" and "Exporters", to "RecordingExtractor" and "SortingExporter" respectively. 

Otherwise, users would get confused about why it's unspported to only convert the format of files by establishing a pipeline with only an extractor and an exporter.

**Comment by rogerhurwitz** [comment]
Done

**Comment by colehurwitz** [comment]
It is? I don't see it in master.

**Comment by rogerhurwitz** [comment]
Hmm, I may have not pushed it.  Please check again.

**Comment by rogerhurwitz** [comment]
Sigh, uploaded a broken version - please try again.

**Comment by colehurwitz** [comment]
Ah, I see it.

**Comment by colehurwitz** [comment]
I think we should change the class element name

**Comment by colehurwitz** [comment]
To RecordingExtractor and SortingExporter

**Comment by rogerhurwitz** [comment]
Makes sense.   Will do.  I'll probably also implement a class level display_name property and remove the hardcoding hack I put into pipeline_view to address the issue in the short term.

**Comment by colehurwitz** [comment]
I will take the picture for the paper now though. Thanks
