### ISSUE TITLE
Automatically add suffix when saving pipelines.

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [SpikeInterface/spikely#64]
Currently (v0.5.2), when saving pipeline models, ".json" won't be autonatically added as suffixes to the filenames, which will make the pipeline model files "invisible" in the loading window. So, it would be better if we could check the filenames inputed by users and automatically add '.json' as suffixes if there is no suffix in them.

I'm not sure whether this is a problem on Linux.

**Comment by rogerhurwitz** [comment]
Yup, this is a problem on both Windows and Linux.  My plan is to add the ".json" extension to the filename if the user doesn't specify it.

**Comment by rogerhurwitz** [comment]
Fixed - please test and close if verified.

**Comment by rogerhurwitz** [comment]
Hi @Shawn-Guo-CN , would you please test this fix and close the issue if it works as requested?

**Comment by Shawn-Guo-CN** [comment]
Thanks very much for reminding. I've tested it and it now works.
