### ISSUE TITLE
Main window crashes when inputting incompatible values for configuring elements.

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [SpikeInterface/spikely#65]
Version: 0.5.2

In the "Configure Parameters" widget, if users input some incompatible value for a parameter, e.g. input "1" as the value of a bool param, the main window will crash and there won't be any warning/reminder to users.

**Comment by rogerhurwitz** [comment]
Hmm, that is not good.  Can you take a look a look at `_convert_value()` in parameter_model.py, and see if you can tell why the exception handler is not getting invoked?

**Comment by Shawn-Guo-CN** [comment]
> Hmm, that is not good. :) Can you take a look a look at `_convert_value()` in parameter_model.py, and see if you can see why the exception handler is not getting invoked?

Sure, I will.

**Comment by Shawn-Guo-CN** [comment]
I just reproduced the error again, and the traceback is given as follow.

```
Traceback (most recent call last):
  File "e:\projects\spikely\spikely\parameter_model.py", line 181, in _convert_value
    raise TypeError(f'{value} is not a valid bool type')
TypeError: 1 is not a valid bool type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\projects\spikely\spikely\parameter_model.py", line 130, in setData
    param_dict['type'], value)
  File "e:\projects\spikely\spikely\parameter_model.py", line 191, in _convert_value
    config.main_window, 'Type Conversion Error', repr(err))
AttributeError: module 'spikely.config' has no attribute 'main_window'
```

**Comment by rogerhurwitz** [comment]
Bingo - that tells me what I need to know.  The joys of dynamic typing - I replaced the global variable `config.main_window` with a function that finds the main window using a PyQt API, but I did not update `_convert_value()`.  Without static type checking that bug remained hidden until you caused that code path to be executed.  I just made the fix and pushed it to master.  Please re-check.

**Comment by Shawn-Guo-CN** [comment]
Just re-run the master branch. This issue has been addressed. Thanks @rogerhurwitz .

**Comment by rogerhurwitz** [comment]
@Shawn-Guo-CN  that was a bad bug - thanks for tracking it down!
