### ISSUE TITLE
Run window improvements

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikely#67]
1. Run windows should have "ok" --> dismisses window without affecting job, and "cancel" --> dismisses window and terminates job.
2. Run windows should have three stages -> Running, Successful Job, Failed Job.
3. Run windows should no longer close automatically.

**Comment by rogerhurwitz** [comment]
1. Was unable to terminate child process using kill or terminate methods on Process object, so left off cancel button for now.
2. Run window now shows that child process is running, has terminated normally, or has exited prematurely.
3. Run window no longer closes automatically - needs to be dismissed by user by pressing "Ok"

**Comment by colehurwitz** [comment]
Nice! Those are two nice improvements. What’s the issue with cancel?

**Comment by Shawn-Guo-CN** [comment]
> 2. Run window now shows that child process is running, has terminated normally, or has exited prematurely.

Thanks very much for this improvement, Roger. I have another question: if a user clicks the button too soon, then he/she still wouldn't know whether the child process exits normally.

This phenomenon can be reproduced by the following steps:
1. run a broken pipeline (by "broken", I mean that the pipeline would definitely raise some error);
2. click the "ok" button as soon as you can after the pop-up of message box;
3. the *stdout* would show that the process terminates prematurely, while there is no signal in the main window.

My personal suggestion would be, set the default state of "ok" button (in message box) to be "deactivated", and set its state to "activated" only after its state is updated. But, this would make users have to wait for the end of a child process and they cannot exit the app during running pipelines.

**Comment by Shawn-Guo-CN** [comment]
Oh, I misunderstood something. There won't be more than 1 message box. So, basically, users cannot get the status of every single running pipeline.

So, users can only get the status of latest running pipeling. And, if there is an error when running the previous pipeline, it can't be shown to users?

**Comment by rogerhurwitz** [comment]
spikely pipeman version pretty much puts these to bed.
