### ISSUE TITLE
Spikely TypeError for np.dtype

### ISSUE THREAD

**Issue by asafbenj** [SpikeInterface/spikely#69]
I am trying to use the BinDatRecordingExtractor in the Spikely GUI, but it seems that no matter what value I put in the mandatory parameter dtype, I get the following error message:

TypeError('np.dtype is not a Spikely supported type')

The actual type of the data is float64, but I also tried inserting just float, int, etc. to see if it changes anything - it doesn't... 

I'm new to Python generally and to Spikely specifically. I'd appreciate very much any help you may be able to provide. Thanks!

**Comment by rogerhurwitz** [comment]
Hi, and thanks for using spikely.  I will take a look at the issue, and get back to you ASAP.

Roger

**Comment by rogerhurwitz** [comment]
Hi @asafbenj 

I believe we found the problem and fixed it.  The latest version of spikely (0.6.4) available either from the master branch of the repository or from using pip install has the fix.  Please check it out and let us know if it is working for you.

Thanks,
Roger

**Comment by asafbenj** [comment]
Indeed - this issue is solved! 
Thank you so much for the super fast fix!

**Comment by rogerhurwitz** [comment]
Cool!  Please let us know if you run into any other bugs or usability issues.  Spikely is still early stage, and this type of feedback is a big help in moving the project forward.
